Console.WriteLine("Введите первое число:");
int Number1 = Console.Read();
Console.WriteLine("Введите второе число:");
int Number2 = Console.Read();
Console.WriteLine(Number2);
Console.WriteLine("Введите третье число:");
int Number3 = Console.Read();
Console.WriteLine(Number3);
Console.WriteLine("Результат сложения трёх чисел");
Console.Write(Number1 + Number2 + Number3);